spring:
  application:
    name: config-client
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
      fail-fast: true
  profiles: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/